apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-starter-deployment
spec:
  selector:
    matchLabels:
      app: kubernetes-starter
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-starter
    spec:
      containers:
        - name: kubernetes-starter
          image: waterfox83/kubernetes-starter:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: EventHubsKey
              valueFrom:
                configMapKeyRef:
                  name: kubernetes-starter-config
                  key: EventHubsKey

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-starter-svc
  labels:
    app: kubernetes-starter
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-starter
  ports:
    - nodePort: 30001
      port: 8080
      targetPort: 8080
